version: '3.8'

services:
  # browse http://localhost:8000/admin-test/
  # then login: admin@prestashop.com / prestashop
  prestashop:
    image: prestashop/prestashop:nightly-8.0
    depends_on:
      - mysql
      - ngrok
    networks:
      - ps_net
    environment:
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWD=admin
      - DB_SERVER=mysql
      - DB_PORT=3306
      - PS_DEMO_MODE=0
      - PS_DOMAIN=replace.me.ngrok.io # will be replaced by tweak script
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=1
      - PS_INSTALL_DB=1
      - PS_ENABLE_SSL=0
      - PS_FOLDER_INSTALL=install
      - PS_FOLDER_ADMIN=ps-admin
      - ADMIN_MAIL=admin@prestashop.com
      - ADMIN_PASSWD=prestashop
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
    volumes:
      - prestashop_data:/var/www/html:rw
      - ./ps_scripts/docker_run_tweak.sh:/tmp/docker_run_tweak.sh:ro
      #- ./ps_scripts/pre_install/:/tmp/pre-install-scripts:ro
      #- ./ps_scripts/post_install/:/tmp/init-scripts/:ro
      #- ./ps_modules:/tmp/modules/:ro
    command: /tmp/docker_run_tweak.sh
    ports:
      - 8000:80

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - ps_net
    expose:
      - '3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--host=localhost', '---user=root', "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql

  ngrok:
    image: wernight/ngrok
    restart: always
    networks:
      - ps_net
    environment:
      - NGROK_BINDTLS=false
      - NGROK_DEBUG=true
      - NGROK_REGION=eu
      - NGROK_PROTOCOL=http
      - NGROK_LOOK_DOMAIN=prestashop
      - NGROK_PORT=80
      - NGROK_AUTH=$NGROK_TOKEN
    ports:
      - 4040:4040

networks:
  ps_net:

volumes:
  mysql_data:
    driver: local
  prestashop_data:
    driver: local
